### ISSUE TITLE
Running node tutorial.js

### ISSUE THREAD

**Issue by jeremykeen** [particle-iot/google-cloud-datastore-tutorial#1]
Where are you instructing the user to run the tutorial code?  I tried to get the pre-reqs running on my Mac. It would be great to walk the user through deploying a vm instance in Google cloud rather than locally.

**Comment by jeremykeen** [comment]
Ok got it going?  Perhaps I do a pull with Mac install using Homebrew?

**Comment by eprphotontest** [comment]
jkeenest-am I stuck at the same part you are/were?  the npm install and run script?

**Comment by jme783** [comment]
Hey all, sorry for the delay on this. I would suggest making sure you run through all the instructions in the [README](https://github.com/spark/google-cloud-datastore-tutorial/blob/master/README.md) to run things locally. That should have everything you need to get spun up. You don't _have to_ run this on a remote server, especially during testing.

When you're ready to have something that runs on a remote server, there are tons of options you can consider. One of the easiest is to use Heroku to[ deploy your Node app](https://devcenter.heroku.com/articles/getting-started-with-nodejs). Let me know if you need more details/have more questions

**Comment by Pedotech** [comment]
Hi done everything but get error messages:
Any help?
Thanks

**Comment by Pedotech** [comment]
MessagesPedros-iMac-2:google-cloud-datastore-tutorial pedrocorreia$ node tutorial.js
Authenticating with Google Cloud...
module.js:538
    throw err;
    ^

Error: Cannot find module 'google-cloud'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/pedrocorreia/google-cloud-datastore-tutorial/tutorial.js:13:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
