### ISSUE TITLE
Errors during 'npm install'

### ISSUE THREAD

**Issue by vervaekejonathan** [particle-iot/google-cloud-datastore-tutorial#8]
Got this error during 'npm install' on ubuntu 17.10

> 
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
> gyp ERR! stack     at emitTwo (events.js:125:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
> gyp ERR! System Linux 4.13.0-36-generic
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/***/projects/google_cloud/google-cloud-datastore-tutorial/node_modules/@google-cloud/compute/node_modules/grpc/src/node/extension_binary/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/***/projects/google_cloud/google-cloud-datastore-tutorial/node_modules/@google-cloud/compute/node_modules/grpc/src/node/extension_binary"
> gyp ERR! cwd /home/***/projects/google_cloud/google-cloud-datastore-tutorial/node_modules/@google-cloud/compute/node_modules/grpc
> gyp ERR! node -v v8.8.1
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok 
> node-pre-gyp ERR! build error 
> node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/***/projects/google_cloud/google-cloud-datastore-tutorial/node_modules/@google-cloud/compute/node_modules/grpc/src/node/extension_binary/grpc_node.node --module_name=grpc_node --module_path=/home/***/projects/google_cloud/google-cloud-datastore-tutorial/node_modules/@google-cloud/compute/node_modules/grpc/src/node/extension_binary' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/***/projects/google_cloud/google-cloud-datastore-tutorial/node_modules/@google-cloud/compute/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> node-pre-gyp ERR! System Linux 4.13.0-36-generic
> node-pre-gyp ERR! command "/usr/bin/node" "/home/***/projects/google_cloud/google-cloud-datastore-tutorial/node_modules/@google-cloud/compute/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd /home/***/projects/google_cloud/google-cloud-datastore-tutorial/node_modules/@google-cloud/compute/node_modules/grpc
> node-pre-gyp ERR! node -v v8.8.1
> node-pre-gyp ERR! node-pre-gyp -v v0.6.28
> node-pre-gyp ERR! not ok 
> Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/***/projects/google_cloud/google-cloud-datastore-tutorial/node_modules/@google-cloud/compute/node_modules/grpc/src/node/extension_binary/grpc_node.node --module_name=grpc_node --module_path=/home/***/projects/google_cloud/google-cloud-datastore-tutorial/node_modules/@google-cloud/compute/node_modules/grpc/src/node/extension_binary' (1)
> npm WARN particle-google-cloud-datastore-tutorial@0.0.1 No repository field.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! grpc@0.14.1 install: `node-pre-gyp install --fallback-to-build`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the grpc@0.14.1 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/***/.npm/_logs/2018-02-25T14_31_09_953Z-debug.log

**Comment by bloomiboy** [comment]
For now, downgrade (or dual install) node to v6.9.0 to overcome this problem. This looks like fixed in a later version of grpc but I haven't gotten to the correct google-cloud/common version to get this fixed for the latest node version.

**Comment by jryd** [comment]
@vervaekejonathan this should be solved by my changes from #10, given it is using the latest packages and therefore there shouldn't be any need to compile the packages from scratch for later versions of Node.

**Comment by schoukah** [comment]
I had this issue as well. 

Installed and used v 6.9.0 and now I get this error message:

> npm ERR! Linux 5.15.0-48-generic
> npm ERR! argv "/***/.nvm/versions/node/v6.9.0/bin/node" "/home/***/.nvm/versions/node/v6.9.0/bin/npm" "install" "@google-cloud/datastore@1.4.0"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8
npm ERR! path /***/google-cloud-datastore-tutorial/node_modules/.staging/@types/bytebuffer-ed47c98b/package.json
npm ERR! code ENOTDIR
npm ERR! errno -20
npm ERR! syscall open

> npm ERR! ENOTDIR: not a directory, open '/home/***/google-cloud-datastore-tutorial/node_modules/.staging/@types/bytebuffer-ed47c98b/package.json'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

> npm ERR! Please include the following file with any support request:
npm ERR!     /home/***/google-cloud-datastore-tutorial/npm-debug.log`
