### ISSUE TITLE
Error at start of tutorial.js

### ISSUE THREAD

**Issue by mwolleben** [particle-iot/google-cloud-datastore-tutorial#9]
Authenticating with Google Cloud...
module.js:540
    throw err;
    ^
Error: Cannot find module 'google-cloud'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/maik_wolleben/google-cloud-datastore-tutorial/tutorial.js:13:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by jryd** [comment]
Did you run `npm install` to install your dependencies?
